name: "Linkedin-RSS"
author: "Arisamiga"
description: "Post the latest post from your RSS Feed to your Linkedin"
inputs:
  feed_list: # Url of RSS
    description: "RSS Link"
    required: true
  ln_access_token: # LinkedIn Access Token
    description: "LinkedIn Access Token | Can be Generated at (https://www.linkedin.com/developers/tools/oauth/)"
    required: true
  embed_image: # Url of embed image
    description: "Url Of image to be used as a embed image on the post"
    required: false
  last_post_path: # Path to the file that stores the last post (Default: .github/.lastPost.txt)
    description: "Path to the file that stores the last post"
    default: ".github/.lastPost.txt"
    required: false
  commit_user: # Username of the commiter
    description: "Username of commit user"
    default: "Linkedin-Post-Action"
    required: false
  commit_email: # Email of the commiter
    description: "Email of commit user"
    default: "linkedin-post-action@example.com"
    required: false
  commit_message: # Commit message
    description: "Commit message"
    default: "Update Last Post File"
    required: false
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "activity"
  color: "blue"
