name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  feed_list:  # Url of RSS
    description: 'RSS Link'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'